hnsSite/hns/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('logout', views.logout, name='logout'),
    path('logout2', views.logoutProfile, name='logoutProfile'),
    path('deleteAccount', views.deleteAccount, name='deleteAccount'),
    path('services/', views.services_list, name='services_list'),
    path('booking/<str:pk>/', views.bookingStep1, name='booking1'),
    path('booking/<str:pk>/<str:description>/<str:date>/<str:time>/<str:address>/<str:aptnum>/<str:zipcode>/', views.bookingStep2, name='booking2'),
    path('booking/<str:pk>/<str:description>/<str:date>/<str:time>/<str:address>/<str:aptnum>/<str:zipcode>/<str:cid>/', views.bookingStep3, name='booking3'),
    path('booking/<str:pk>/<str:description>/<str:date>/<str:time>/<str:address>/<str:aptnum>/<str:zipcode>/<str:cid>/<str:pid>/', views.bookingConfirmation, name='booking4'),
    path('booking/complete/<str:pk>/', views.completeContract, name='bookingDone'),
    path('becomeContractor/', views.becomeContractor, name='becomeContractor'),
    path('becomeContractor/complete/', views.doneContractorApp, name='doneContractorApp'),
    path('login/', views.login, name='login'),
    path('create_account/', views.createUserAccount, name="createUserAccount"),
    path('account/user_profile/', views.userProfile, name='userProfile'),
    path('account/user_profile/edit', views.userProfileEdit, name='userProfile_edit'),
    path('account/payment_methods/', views.userPayment, name='userPayment'),
    path('account/booking_history/', views.userBookingInfo, name='userBooking'),
    path('contractor/contractor_login/', views.contractorLogin, name='loginContractor'),
    path('contractor/contractor_profile/', views.contractorProfile, name='contractorProfile'),
    path('contractor/contractor_profile/edit', views.contractorProfileEdit, name='contractorProfile_edit'),
    path('contractor/service_record/', views.contractorServices, name='contractorServices'),
    path('contractor/service_record/apply', views.contractorServiceApp, name='contractorServiceApp'),
    path('contractor/rating_record/', views.contractorRatings, name='contractorRatings'),
    path('contractor/contract_history/', views.contractorContracts, name='contractorContracts'),
    path('contractor/schedule/', views.contractorSchedule, name='contractorSchedule'),
    path('administrator/admin_login/', views.adminLogin, name='loginAdministrator'),
    path('administrator/admin_profile/', views.adminProfile, name='administratorProfile'),
    path('administrator/users/', views.manageUsers, name='manageUsers'),
    path('administrator/contractors/', views.manageContractors, name='manageContractors'),
    path('administrator/contractor_applications/', views.manageContractorApp, name='manageApp1'),
    path('administrator/contractor_applications/approve/<str:id>', views.adminApproveApp, name='approveApp1'),
    path('administrator/contractor_applications/reject/<str:id>', views.adminRejectApp, name='rejectApp1'),
    path('administrator/service_applications/', views.manageServiceApp, name='manageApp2'),
    path('administrator/service_applications/approve/<str:id>', views.adminApproveApp2, name='approveApp2'),
    path('administrator/service_applications/reject/<str:id>', views.adminRejectApp2, name='rejectApp2'),
    path('administrator/<str:accountType>/<str:id>', views.adminDeleteAccount, name='adminDeleteAccount'),
    path('administrator/users/edit/<str:id>', views.adminEditUser, name='adminEditUser'),
    path('administrator/contractors/edit/<str:id>', views.adminEditContractor, name='adminEditContractor'),
    path('error/<int:id>', views.errorPages, name="error"),
]

hnsSite/hnsSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hns.urls'))
]

hnsSite/hns/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import datetime

class Administrators(models.Model):
    adminid = models.IntegerField(db_column='adminID', primary_key=True)  # Field name made lowercase.
    adminemail = models.CharField(db_column='adminEmail', max_length=100)  # Field name made lowercase.
    adminpassword = models.CharField(db_column='adminPassword', max_length=50)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'administrators'


class Contractpayment(models.Model):
    contractid = models.ForeignKey('Contracts', models.DO_NOTHING, db_column='contractID', primary_key=True, default=1)  # Field name made lowercase.
    time = models.DateTimeField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    approved = models.IntegerField()
    refund = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'contractPayment'


class Contractorapplications(models.Model):
    contractorid = models.IntegerField(db_column='contractorID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(max_length=100)
    ssn = models.IntegerField(unique=True)
    address = models.CharField(max_length=150)
    aptnum = models.CharField(db_column='aptNum', max_length=10)  # Field name made lowercase.
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    willingtravel = models.IntegerField(db_column='willingTravel')  # Field name made lowercase.
    phone = models.CharField(max_length=15)
    dob = models.DateField()
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)
    dateapp = models.DateField(db_column='dateApp')  # Field name made lowercase.
    adminid = models.ForeignKey(Administrators, models.DO_NOTHING, db_column='adminID', default=None)  # Field name made lowercase.
    dateapproved = models.DateField(db_column='dateApproved', default=None)  # Field name made lowercase.

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'contractorApplications'


class Contractors(models.Model):
    contractorid = models.ForeignKey(Contractorapplications, models.DO_NOTHING, db_column='contractorID', primary_key=True, default=1)  # Field name made lowercase.
    name = models.CharField(max_length=100)
    ssn = models.IntegerField(unique=True)
    scheduleid = models.IntegerField(db_column='scheduleID', unique=True)  # Field name made lowercase.
    address = models.CharField(max_length=150)
    aptnum = models.CharField(db_column='aptNum', max_length=10)  # Field name made lowercase.
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField(db_column='zipCode')  # Field name made lowercase.
    willingtravel = models.IntegerField(db_column='willingTravel')  # Field name made lowercase.
    phone = models.CharField(max_length=15)
    dob = models.DateField()
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'contractors'


class Contractorsservicerecords(models.Model):
    contractorid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='contractorID', primary_key=True, default=1)  # Field name made lowercase.
    serviceid = models.ForeignKey('Services', models.DO_NOTHING, db_column='serviceID')  # Field name made lowercase.
    chargeservice = models.DecimalField(db_column='chargeService', max_digits=10, decimal_places=2)  # Field name made lowercase.
    yearsexperience = models.IntegerField(db_column='yearsExperience')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'contractorsServiceRecords'
        unique_together = (('contractorid', 'serviceid'),)


class ContractorsBackground(models.Model):
    contractorid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='contractorID', primary_key=True, default=1)  # Field name made lowercase.
    approved = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'contractors_background'


class Contracts(models.Model):
    contractid = models.IntegerField(db_column='contractID', primary_key=True)  # Field name made lowercase.
    serviceid = models.ForeignKey('Services', models.DO_NOTHING, db_column='serviceID', default=1)  # Field name made lowercase.
    userid = models.ForeignKey('Users', models.DO_NOTHING, db_column='userID', default=1)  # Field name made lowercase.
    description = models.CharField(max_length=500)
    dateservice = models.DateField(db_column='dateService')  # Field name made lowercase.
    starttime = models.TimeField(db_column='startTime')  # Field name made lowercase.
    servicezipcode = models.IntegerField(db_column='serviceZipCode')  # Field name made lowercase.
    serviceaddress = models.CharField(db_column='serviceAddress', max_length=150)  # Field name made lowercase.
    serviceaptnum = models.CharField(db_column='serviceAptNum', max_length=10)  # Field name made lowercase.
    contractorid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='contractorID', default=1)  # Field name made lowercase.
    paymentid = models.ForeignKey('Paymentinfo', models.DO_NOTHING, db_column='paymentID', default=1)  # Field name made lowercase.
    datecontract = models.DateTimeField(db_column='dateContract')  # Field name made lowercase.
    cancelcontract = models.IntegerField(db_column='cancelContract')  # Field name made lowercase.

    def __str__(self):
        return self.description

    class Meta:
        managed = True
        db_table = 'contracts'


class Paymentinfo(models.Model):
    paymentid = models.IntegerField(db_column='paymentID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('Users', models.DO_NOTHING, db_column='userID', default=1)  # Field name made lowercase.
    cardtype = models.CharField(db_column='cardType', max_length=20)  # Field name made lowercase.
    cardname = models.CharField(db_column='cardName', max_length=150)  # Field name made lowercase.
    cardnumber = models.IntegerField(db_column='cardNumber')  # Field name made lowercase.
    cvv = models.IntegerField()
    billingaddress = models.CharField(db_column='billingAddress', max_length=150)  # Field name made lowercase.
    expdate = models.DateField(db_column='expDate')  # Field name made lowercase.

    def __str__(self):
        return str(self.cardnumber)

    class Meta:
        managed = True
        db_table = 'paymentInfo'


class Rating(models.Model):
    contractorid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='contractorID', primary_key=True, default=1)  # Field name made lowercase.
    userid = models.ForeignKey('Users', models.DO_NOTHING, db_column='userID', default=1)  # Field name made lowercase.
    number_rating = models.IntegerField()
    title = models.CharField(max_length=50)
    comments = models.CharField(max_length=300)
    date = models.DateTimeField()

    def __str__(self):
        return self.title

    class Meta:
        managed = True
        db_table = 'rating'
        unique_together = (('contractorid', 'userid'),)


class Schedules(models.Model):
    scheduleid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='scheduleID', primary_key=True, default=1)  # Field name made lowercase.
    time_slot = models.ForeignKey('TimeSlots', models.DO_NOTHING, db_column='time_slot_ID', default=1)  # Field name made lowercase.
    busy_available = models.IntegerField(db_column='busy/available')  # Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'schedules'
        unique_together = (('scheduleid', 'time_slot'),)


class Serviceapplications(models.Model):
    serviceappid = models.IntegerField(db_column='serviceAppID', primary_key=True)  # Field name made lowercase.
    contractorid = models.ForeignKey(Contractors, models.DO_NOTHING, db_column='contractorID', default=1)  # Field name made lowercase.
    serviceid = models.ForeignKey('Services', models.DO_NOTHING, db_column='serviceID', default=1)  # Field name made lowercase.
    chargeservice = models.DecimalField(db_column='chargeService', max_digits=10, decimal_places=2, default=7.25)  # Field name made lowercase.
    yearsexperience = models.IntegerField(db_column='yearsExperience', default=0)  # Field name made lowercase.
    dateapp = models.DateField(db_column='dateApp')  # Field name made lowercase.
    adminid = models.ForeignKey(Administrators, models.DO_NOTHING, db_column='adminID', default=None)  # Field name made lowercase.
    dateapproved = models.DateField(db_column='dateApproved', default=None)  # Field name made lowercase.

    def __str__(self):
        return self.serviceappid

    class Meta:
        managed = True
        db_table = 'serviceApplications'
        unique_together = (('serviceappid', 'serviceid'),)


class Servicecategories(models.Model):
    categoryserviceid = models.IntegerField(db_column='categoryServiceID', primary_key=True)  # Field name made lowercase.
    sub_name = models.CharField(max_length=100)

    def __str__(self):
        return self.sub_name

    class Meta:
        managed = False
        db_table = 'serviceCategories'


class Services(models.Model):

hnsSite/hns/templates/booking/availableContractors.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <title>Booking A Service</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'hns/css/style.css' %}" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    </head>
   
    <body>
        <div class="topnav">
            <div class="topnav_logo">
                <a href="{% url 'home' %}">HomeNeedsService</a>
            </div>
            
            <div class="topnav_menu">
                <a href="{% url 'home' %}">Home</a>
                <a class="active" href="{% url 'services_list' %}" disabled="disabled">Services</a>
                <a href="{% url 'becomeContractor' %}">Become A Contractor</a>
                {% if have_user %}
                    <div class="dropdown">
                        <button class="dropbtn">My Account 
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <a href="{% url 'userProfile' %}">Profile</a>
                            <a href="{% url 'userBooking' %}">Booking History</a>
                            <a href="{% url 'userPayment' %}">Payment Methods</a>
                            <a href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </div>
                {% elif have_contractor %}
                <div class="dropdown">
                    <button class="dropbtn">My Account 
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'contractorProfile' %}">Profile</a>
                        <a href="{% url 'contractorServices' %}">Service Record</a>
                        <a href="{% url 'contractorRatings' %}">Rating Record</a>
                        <a href="{% url 'contractorContracts' %}">Contract History</a>
                        <a href="{% url 'contractorSchedule' %}">My Schedule</a>
                        <a href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
                {% elif have_admin %}
                <div class="dropdown">
                    <button class="dropbtn">My Account 
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'administratorProfile' %}">Profile</a>
                        <a href="{% url 'manageUsers' %}">Manage Users</a>
                        <a href="{% url 'manageContractors' %}">Manage Contractors</a>
                        <a href="{% url 'manageApp1' %}">Manage Contractors Applications</a>
                        <a href="{% url 'manageApp2' %}">Manage Add Service Applications</a>
                        <a href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
        </div>
        
        <div class="pageContent">
            <h2 class="header">Booking - {{service}}</h2>
            
            {% if availableContractors %}
            <p>Select a Contractor.</p>

            {% for message in messages %}
                <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>

                    {{ message }}

                </div>
            {% endfor %}
           
            <form class="selectContractor">
                {% for contractor in availableContractors %}
                    <div class="contractorData">
                        <input type="radio" name="buttonContractor" value="{{contractor.contractorid.contractorid.contractorid}}">
                        <label for="{{contractor.contractorid.contractorid.contractorid}}"><span><span></span></span>{{contractor.contractorid}}</label>
                    </div>
                {% endfor %}

                <div class="controlBooking">
                    <input type="submit" name="Get Contractors" value="Continue to Payment">
                    <a class="btn_link" href="{% url 'services_list' %}">Cancel</a>
                </div>
            </form>
            {% else %}
            <h3>We are sorry, but there are no contractors that offer this service.</h3>
            {% endif %}
           
        </div>

        <footer>
            <!-- Footer main -->
            <section class="ft-main">
              <div class="ft-main-item">
                <ul>
                  <li><a href="{% url 'services_list' %}">Services</a></li>
                  <li><a href="{% url 'becomeContractor' %}">Become A Contractor</a></li>
                  <li><a href="{% url 'login' %}">User Account</a></li>
                  <li><a href="{% url 'loginContractor' %}">Contractor Account</a></li>
                  <li><a href="{% url 'loginAdministrator' %}">Administrator Account</a></li>
                </ul>
              </div>
              <div class="ft-main-item">
                <a href="#">Contact Us</a>
              </div>
            </section>
          
            <!-- Footer legal -->
            <section class="ft-legal">
              <ul class="ft-legal-list">
                <li><a href="#">Terms &amp; Conditions</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li>&copy;2020 Group 3 - Fix-it-Felix.</li>
              </ul>
            </section>
        </footer>
    </body>

</html>

hnsSite/hns/templates/booking/bookingInformation.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <title>Booking A Service</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'hns/css/style.css' %}" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script>
            function myFunction2() {
                var x = document.getElementById("myDIV");
                if (x.style.display === "none") {
                    x.style.display = "block";
                } else {
                    x.style.display = "none";
                }
            }
        </script>
        <script>
            $( function() {
                $( "#id_dateservice" ).datepicker({dateFormat: 'yy-mm-dd', minDate: new Date(), maxDate: new Date(new Date().setMonth(new Date().getMonth() + 3))});
                $('#id_starttime').timepicker({
                    timeFormat: 'h:mm p',
                    interval: 30,
                    minTime: '8',
                    maxTime: '6:00pm',
                    defaultTime: '11',
                    startTime: '8:00',
                    dynamic: false,
                    dropdown: true,
                    scrollbar: true
                });
                $( "#id_dateservice" ).on('keydown paste', function(e){
                    e.preventDefault();
                })
            } );
        </script>
    </head>
   
    <body>
        <div class="topnav">
            <div class="topnav_logo">
                <a href="{% url 'home' %}">HomeNeedsService</a>
            </div>
            
            <div class="topnav_menu">
                <a href="{% url 'home' %}">Home</a>
                <a class="active" href="{% url 'services_list' %}" disabled="disabled">Services</a>
                <a href="{% url 'becomeContractor' %}">Become A Contractor</a>
                {% if have_user %}
                    <div class="dropdown">
                        <button class="dropbtn">My Account 
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <a href="{% url 'userProfile' %}">Profile</a>
                            <a href="{% url 'userBooking' %}">Booking History</a>
                            <a href="{% url 'userPayment' %}">Payment Methods</a>
                            <a href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </div>
                {% elif have_contractor %}
                <div class="dropdown">
                    <button class="dropbtn">My Account 
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'contractorProfile' %}">Profile</a>
                        <a href="{% url 'contractorServices' %}">Service Record</a>
                        <a href="{% url 'contractorRatings' %}">Rating Record</a>
                        <a href="{% url 'contractorContracts' %}">Contract History</a>
                        <a href="{% url 'contractorSchedule' %}">My Schedule</a>
                        <a href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
                {% elif have_admin %}
                <div class="dropdown">
                    <button class="dropbtn">My Account 
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'administratorProfile' %}">Profile</a>
                        <a href="{% url 'manageUsers' %}">Manage Users</a>
                        <a href="{% url 'manageContractors' %}">Manage Contractors</a>
                        <a href="{% url 'manageApp1' %}">Manage Contractors Applications</a>
                        <a href="{% url 'manageApp2' %}">Manage Add Service Applications</a>
                        <a href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
        </div>
        
        <div class="pageContent">
            <h2 class="header">Booking - {{service}}</h2>
            
            {% if have_user %}
                <p>Enter information required below.</p>

                {% for message in messages %}
                    <div id="myDIV" class="alert alert-success">
                        <i class="fa fa-close" onclick="myFunction2()"></i>

                        {{ message }}

                    </div>
                {% endfor %}
                <form class="bookingForm" method="POST">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th colspan="2">Description</th>
                        </tr>
                        <tr>
                            <td colspan="2">{{form.description}}</td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <th>Start Time</th>
                        </tr>
                        <tr>
                            <td>{{form.dateservice}}</td>
                            <td>{{form.starttime}}</td>
                        </tr>
                        <tr>
                            <th colspan="2">Service Location</th>
                        </tr>
                        <tr>
                            <th colspan="2">Address</th>
                        </tr>
                        <tr>
                            <td colspan="2">{{form.serviceaddress}}</td>
                        </tr>
                        <tr>
                            <th>Apt. Number</th>
                            <th>Zip Code</th>
                        </tr>
                        <tr>
                            <td>{{form.serviceaptnum}}</td>
                            <td>{{form.servicezipcode}}</td>
                        </tr>
                    </table>
                    
                    <div class="controlBooking">
                        <input type="submit" name="Get Contractors" value="Get Available Contractors">
                        <a class="btn_link" href="{% url 'services_list' %}">Cancel</a>
                    </div>
                </form>
            {% else %}
                <p>You need to be logged in to book service.</p>

                <div class="bookingUser">
                    <a class="btn_link" href="{% url 'login' %}">Login</a>
                    <a class="btn_link" href="{% url 'createUserAccount' %}" disable="disabled">Create an Account</a>
                </div>
            {% endif %}
        </div>

        <footer>
            <!-- Footer main -->
            <section class="ft-main">
              <div class="ft-main-item">
                <ul>
                  <li><a href="{% url 'services_list' %}">Services</a></li>
                  <li><a href="{% url 'becomeContractor' %}">Become A Contractor</a></li>
                  <li><a href="{% url 'login' %}">User Account</a></li>
                  <li><a href="{% url 'loginContractor' %}">Contractor Account</a></li>
                  <li><a href="{% url 'loginAdministrator' %}">Administrator Account</a></li>
                </ul>
              </div>
              <div class="ft-main-item">
                <a href="#">Contact Us</a>
              </div>
            </section>
          
            <!-- Footer legal -->
            <section class="ft-legal">
              <ul class="ft-legal-list">
                <li><a href="#">Terms &amp; Conditions</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li>&copy;2020 Group 3 - Fix-it-Felix.</li>
              </ul>
            </section>
        </footer>
    </body>

</html>